main: de.raidcraft.rctravel.RCTravelPlugin
name: RCTravel
version: ${project.version}#${BUILDS_ALL_TIME}
description: Provides player travel.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]
database: true

